kind = "DojoContract"
class_hash = "0x177e5fa566aebe57474410ec3968e77fe5c598ea3ae85531ea6ae59b12e3dd7"
original_class_hash = "0x177e5fa566aebe57474410ec3968e77fe5c598ea3ae85531ea6ae59b12e3dd7"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
