kind = "DojoModel"
class_hash = "0x1550b8551387771c221d7089785d44d4b20a484781c4815dfdc72e57fd74dfa"
original_class_hash = "0x1550b8551387771c221d7089785d44d4b20a484781c4815dfdc72e57fd74dfa"
abi = "manifests/dev/abis/base/models/dojo_starter_models_game_game.json"
name = "dojo_starter::models::game::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "player1"
type = "ContractAddress"
key = false

[[members]]
name = "player2"
type = "ContractAddress"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "board"
type = "Board"
key = false
